### ISSUE TITLE
Problème affichage après tri

### ISSUE THREAD

**Issue by corzakiewicz** [departement-maine-et-loire/mycustomview#12]
Bonjour,

Depuis "Ma Vue personnalisée", je dispose d'une vue incluant quatre recherches sauvegardées.
Sur la vue "Tickets en Cours" (qui liste environ 90 tickets), je clique sur Dernière Modification de façon à afficher en premier ceux dont la date de modification est la plus récente. Malheureusement, ceux qui s'affichent en premier ne sont pas ceux dont la date de modification est la plus récente, mais ceux dont la date de modification est deux ou trois jours avant.
Dans l'exemple ci-dessous, je devrais avoir des tickets avec une date de modification du 08 Mars, hors, ça m'affiche ceux du 06 Mars.
Un peu comme si la vue qui devrait comporter plusieurs pages (puisque envrion 90 tickets en tout) ne m'affichait pas la première page mais la seconde.

![image](https://github.com/departement-maine-et-loire/mycustomview/assets/75740722/f73b41bd-7400-4224-891e-9d7e81550acd)

En revanche, si je clique sur le titre de la Recherche Sauvegardée, "Tickets en cours" dans mon exemple, alors une autre page s'ouvre avec la liste de tous les tickets de cette Recherche Sauvegardée, et là, lorsque je clique sur la colonne "Dernière modification", mes tickets du 08 Mars apparaissent bien en premier.

Sauriez-vous comment je dois procéder pour faire en sorte que les tickets modifiés le plus récemment apparaissent bien premier lors d'un tri sur Date de dernière modification dans Ma Vue Personnalisée ?

Par avance merci à vous.

Versions utilisées :
- GLPI v10.0.7
- MyCustomView v2.0.1

**Comment by YannickComba** [comment]
Bonjour,

Cet incident survient effectivement lorsque le nombre de données dépassent celles du filtre, la fonction de tri ne fonctionnant que sur les données affichées (si les 5 dernières données sont affichées, cela ne triera que sur ces 5 mêmes données).

Avec la version 2.0.3 vous devrez enregistrer l'ordre de tri lors de la sauvegarde de votre recherche. Cependant, la fonction de tri continuera de ne fonctionner que sur les données affichées.

**Comment by corzakiewicz** [comment]
Bonjour,
Merci encore pour votre réactivité.
J'ai installé la v2.0.3
Ma Recherche Sauvegardée est bien déjà enregistrée avec un tri sur la date de modification.
Pour autant, dans la Vue Personnalisée, ça n'affiche toujours pas correctement : ça n'a pas changé, je suis toujours dans le cas décrit initialement dans ce ticket.
Peut-être y'aurait-il quelque chose que je ne ferai pas correctement. Si vous avez besoin de précision ou des indications à me donner, je suis preneur.
Merci.

**Comment by YannickComba** [comment]
Bonjour,

Avez-vous la possibilité de regarder la recherche sauvegardée en base de donnée ?
Elle devrait se trouver dans la table : glpi_savedsearches

Pour trouver l'ID de votre recherche, vous devriez l'avoir en allant dans Outils > Recherches sauvegardées > votreRecherche.
Si vous pouviez m'indiquer ce qui se trouve dans la colonne "query" de la ligne en question.

Cela devrait ressembler à ça : 
```
is_deleted=0&as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=notold&itemtype=Ticket&sort%5B0%5D=19&order%5B0%5D=DESC
```

Cordialement.

**Comment by corzakiewicz** [comment]
l'id de la recherche sauvegardée est : 49
Et voici le contenu de la colonne query de celle-ci :

is_deleted=0&as_map=0&criteria%5B0%5D%5Blink%5D=AND%20NOT&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=6&criteria%5B1%5D%5Blink%5D=AND%20NOT&criteria%5B1%5D%5Bfield%5D=12&criteria%5B1%5D%5Bsearchtype%5D=equals&criteria%5B1%5D%5Bvalue%5D=5&criteria%5B2%5D%5Blink%5D=AND&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Blink%5D=AND&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bvalue%5D=86&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bvalue%5D=204&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bvalue%5D=422&criteria%5B2%5D%5Bcriteria%5D%5B3%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B3%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B3%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B3%5D%5Bvalue%5D=203&criteria%5B2%5D%5Bcriteria%5D%5B4%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B4%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B4%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B4%5D%5Bvalue%5D=869&search=Rechercher&itemtype=Ticket


Et voici dans l'inteface graphique comment est définie la Recherche Sauvegardée :

![image](https://github.com/departement-maine-et-loire/mycustomview/assets/75740722/bda7d361-3b7c-48a8-b799-cdff4b364c66)

**Comment by YannickComba** [comment]
Bonjour, 

Au vu de la commande, la recherche n'a pas été sauvegardé en étant trié au prélable, voici un exemple ci-dessous :
Dans la BDD : 
```
is_deleted=0&as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND%20NOT&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=6&criteria%5B1%5D%5Blink%5D=AND%20NOT&criteria%5B1%5D%5Bfield%5D=12&criteria%5B1%5D%5Bsearchtype%5D=equals&criteria%5B1%5D%5Bvalue%5D=5&criteria%5B2%5D%5Blink%5D=AND&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Blink%5D=AND&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B0%5D%5Bvalue%5D=myself&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B1%5D%5Bvalue%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Blink%5D=OR&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bfield%5D=5&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bsearchtype%5D=equals&criteria%5B2%5D%5Bcriteria%5D%5B2%5D%5Bvalue%5D=2&itemtype=Ticket&sort%5B0%5D=19&order%5B0%5D=DESC
```
On peut voir à la fin de la recherche enregistrée "&sort%5B0%5D=19&order%5B0%5D=DESC" (19 étant le tri par dernière date de modification et DESC étant l'ordre décroissant, donc du plus récent au moins récent)

Voici à quoi ressemble l'interface graphique : 

![Capture2](https://github.com/departement-maine-et-loire/mycustomview/assets/136609218/e19cceb5-dd04-40de-aa04-4494a37bbf8a)

Essayez de ré-enregistrer votre recherche avec ce tri et dîtes moi si cela a corrigé votre incident.

Cordialement.

**Comment by corzakiewicz** [comment]
C'est bien résolu grâce à vos instructions.
Merci beaucoup pour votre aide et bonne continuation.
