### ISSUE TITLE
Is the plugin compatible with 10.0.10 ?

### ISSUE THREAD

**Issue by CelexisCode** [departement-maine-et-loire/mycustomview#14]
Hello,

Is the plugin compatible with GLPI 10.0.10 ?

Regards,

**Comment by YannickComba** [comment]
Hello,

Yes it is compatible.

Regards.

**Comment by CelexisCode** [comment]
Je n'avais pas vu que vous êtiez francais ! 

Il est impossible de trouver le plugin depuis l'interface web GLPI avec le marketplace.
Je pense que c'est parce que la version renseignée dans le marketplace est "10.0" et pas "~10.0".

Cdt,

**Comment by YannickComba** [comment]
Bonjour,
 
L'apparition du plugin sur le Marketplace n'est pas lié à la version renseignée, celle-ci est dépendante de la volonté de Teclib.
Nous leur avons adressé plusieurs mails à ce sujet et sommes toujours à ce jour en attente de publications de leur part ou de justification quant à un éventuel refus.
 
Cordialement.
