### ISSUE TITLE
Feature Request - Auto Refresh

### ISSUE THREAD

**Issue by CelexisCode** [departement-maine-et-loire/mycustomview#15]
Bonjour,

Une fonction d'auto refresh serait super !

Cordialement,

**Comment by YannickComba** [comment]
Bonjour,

GLPI n'ayant nativement pas de fonction d'auto refresh et celle-ci pouvant avoir un impact assez lourd au niveau des performances, ce n'est pas prévu de l'implémenter actuellement.

Cordialement.
