### ISSUE TITLE
Nouvel utilisateur : les recherches sauvegardées ne s'ajoutent pas à la vue

### ISSUE THREAD

**Issue by corzakiewicz** [departement-maine-et-loire/mycustomview#16]
Bonjour,
J'ai défini un nouvel utilisateur dans GLPI et l'ai autorisé à utiliser MyCustomView.
J'essaie de lui définir une vue dans "Ma Vue Personnalisée" mais ça ne fonctionne pas : je peux choisir la ou les recherches sauvegardées à ajouter dans la vue mais la recherche ne s'affiche pas dans la vue.
Voici comment je procède : j'ouvre "Ma vue personnalisée", je clique sur "Modifier", je clique sur "Liste", je clique sur le bouton "+" à côté de la recherche sauvegardée souhaitée, le message "La recherche a été sauvegardée" apparait bien en bas à droite dans GLPI seulement la recherche n'est pas ajoutée à la vue.

Je ne rencontre pas ce problème avec des utilisateurs qui disposaient déjà d'une vue MyCustomView.

Savez-vous comment je pourrais résoudre le problème ?

Merci à vous.

**Comment by YannickComba** [comment]
Bonjour, 

L'incident provenait du fait que si un utilisateur utilisait une recherche publique autre que la sienne, cela la supprimait et la rendait inutilisable. La version 2.0.4 corrige cet incident.
Si vous avez encore cet incident, n'hésitez pas à nous recontacter.

Cordialement.

**Comment by corzakiewicz** [comment]
Le problème est bien résolu grâce à la v2.0.4
Merci beaucoup pour votre aide et votre rapidité très appréciable !
Bonne journée à vous.
