### ISSUE TITLE
 the plugin only works with the debug mode option enabled

### ISSUE THREAD

**Issue by r0bertk** [departement-maine-et-loire/mycustomview#18]
Hello, 
i install version 2.0.4  on GLPI 10.0.14

the plugin only works with the debug mode option enabled, when I disable debug mode the appearance is bad.
![image](https://github.com/departement-maine-et-loire/mycustomview/assets/13787190/1918d827-dcd6-475d-8b72-6b07888845aa)

**Comment by YannickComba** [comment]
Hello,

It seems that CSS didn't load. I'll need more informations to understand your issue : 

 - Is the issue happening with previous version ?
 - Is the issue happening in private browser ?
 - Is the issue happening in another browser ?
 - Is the issue happening with all profiles ?
 - Are you using your own CSS with GLPI ?

Regards.

**Comment by r0bertk** [comment]
Hi,
Thank you for your reply. After analysis, it turned out that it was enough to disable the cache. I was confused by the fact that the same thing happened in all my browsers, i.e. firefox, edge, chrome. The topic can be closed
