### ISSUE TITLE
Possibilité d'ajouter les recherches publiques ?

### ISSUE THREAD

**Issue by corzakiewicz** [departement-maine-et-loire/mycustomview#2]
Bonjour,
Bravo pour votre travail et merci de l'avoir mis à disposition de la communauté, nous recherchions ce type de solution depuis longtemps sans disposer des compétences en développement.
Y-a-t-il une possibilité simple de permettre d'ajouter des Recherches Sauvegardées Publiques dans Ma Vue Personnalisée ?
Merci.

**Comment by MaximeMeriot** [comment]
Bonjour et merci de votre retour.
Une mise à jour est disponible : [https://github.com/departement-maine-et-loire/mycustomview/releases/tag/1.2.1](url)
Vous pourrez maintenant ajouter des recherches sauvegardées publiques depuis la liste en bas de page.

Cordialement,
Maxime.

**Comment by corzakiewicz** [comment]
Bonjour,
J'ai installé et testé avec succès la nouvelle version, ça répond bien au besoin : merci beaucoup !

**Comment by MaximeMeriot** [comment]
Merci à vous pour cette proposition d'ajout ! 

Je me permets de clôturer. 

Maxime.
