### ISSUE TITLE
Probleme en cours planifiés

### ISSUE THREAD

**Issue by Pliploupla** [departement-maine-et-loire/mycustomview#4]
Salut !

J'ai mes recherches sauvegardées qui fonctionnent
Mais quand j'use le plugin, les en cours planifiés ne s'affichent pas tout le temps ...?

Pourquoi ?

Thxs

**Comment by departement-maine-et-loire** [comment]
Bonjour ,

Difficile d’investiguer sur ce problème avec si peu d’informations :
- Quelle est la version GLPI utilisée ?
- Est-ce que le bug a été reproduit sur un autre environnement GLPI ?
- Quelle est la requête exacte de la recherche sauvegardée appelée par le plugin ?
- Est-ce que la recherche est publique ?
- Est-ce que le mode debug (mode admin) indique des erreurs ? Si oui, lesquelles ?
- Est-ce que les logs serveurs remontent des erreurs ? Si oui lesquelles ?
- Possibilité d’avoir une capture d’écran du bug ?
- Le bug est-il aléatoire ? ou intervient-il à une heure précise ?
- Est-ce qu’en appelant la recherche sauvegardée directement (après apparition du bug avec le plugin), le problème survient ?
- N’y a-t-il pas des données formatées différemment qui sortent de l’ordinaire ?

Merci

**Comment by departement-maine-et-loire** [comment]
Bonjour, nous arrêtons le développement pour une version compatible GLPI v9, nous clôturons donc votre issue. Si jamais vous avez migré vers GLPI 10, nous vous invitons à utiliser _MyCustomView_ 2.0 récemment publiée. Cordialement
