### ISSUE TITLE
Impossible d'afficher les liste

### ISSUE THREAD

**Issue by Nicog35** [departement-maine-et-loire/mycustomview#5]
Bonjour, je viens d'installer mycustomview sur mon GLPI (9.4.5), j'ai bien des recherches sauvegardés dans mon GLPI mais le plugin n'en trouve aucune ? Avez vous un idée ?
Merci

**Comment by departement-maine-et-loire** [comment]
Bonjour,

Pouvez-vous effectuer les vérifications suivantes :
- Droits effectifs sur le profil utilisé (Administration/Profils puis onglet "Ma vue personnalisée")
- Entité de la recherche sauvegardée identique à celle de l'entité sur laquelle vous êtes positionné lorsque vous utilisez la vue personnalisée

Puis, une fois les vérifications faites, testez l'appel direct de la recherche sauvegardée et vérifiez si vous obtenez un résultat.
Si vous activez le mode Debug, et que vous vous positionnez ensuite sur la vue personnalisée, avez-vous une erreur ?

Merci de vos retours.

**Comment by Nicog35** [comment]
Bonjour,
Les droits effectif sont bien ok

![image](https://user-images.githubusercontent.com/104827161/166447617-8122f5b4-2832-4b5e-878c-aede427177f0.png)

Nous avons une seul entité donc ok

Et un appel direct depuis les recherche sauvegarder fonctionne correctement, d’ailleurs je me questionnais si elle devais être public ? 
En mode débug aucun problème.

**Comment by departement-maine-et-loire** [comment]
Bonjour

Pouvez-vous essayer avec un autre navigateur vidé de son cache (afin d'éliminer cette cause, même si c'est peu probable) ?
Ensuite, sans plus d'éléments, je ne vois que la solution de désinstaller/réinstaller le plugin.


D'autre part, le fait d'avoir des recherches sauvegardées publiques ou privées est indépendant du plugin. Tout dépend à qui doit s'adresser ces dernières.
Dans tous les cas, le plugin gère les deux.

**Comment by Nicog35** [comment]
Bonjour,

J'ai fais le test sur un autre navigateur et même sur un autre poste, j'ai le même problème.
Par contre je remarque que sous un autre utilisateur admin il n'a pas le plugin de visible alors qu'il a les droit !!

![image](https://user-images.githubusercontent.com/104827161/166643641-7259f05a-c2a9-4857-87c5-c2e2f0e7ffc0.png)


Si cela vous intéresse de creuser nous pourrions éventuellement rentré en contact pour que vous puissiez regarder via une télémaintenance par exemple !
Je vous donne mon mail si cela vous tente : ngouaillier@aberproprete.fr

Merci pour votre temps.

**Comment by Nicog35** [comment]
Pardon je reprend sur mon poste après reconnexion il a bien le plugin mais pas de vue comme mon profil finalement ....

**Comment by Nicog35** [comment]
Est ce que vous pouvez me dire sur quoi ce base la recherche dans le Mysql que je puisse vérifier les données ?

**Comment by departement-maine-et-loire** [comment]
Bonjour, nous arrêtons le développement pour une version compatible GLPI v9, nous clôturons donc votre issue. Si jamais vous avez migré vers GLPI 10, nous vous invitons à utiliser MyCustomView 2.0 récemment publiée. Cordialement.
