### ISSUE TITLE
Ajout bouton page précédente/suivante et bug sur le paramètre Nombre d'élément par recherche

### ISSUE THREAD

**Issue by c-theo** [departement-maine-et-loire/mycustomview#6]
Bonjour et d'abord merci pour ce plugin !

Serait-il possible d'ajouter un bouton pour chaque vue, permettant de parcourir les pages précédentes/suivantes, lorsque le nombre d'éléments ne tient pas sur une page ?

De plus, j'ai remarqué que le paramètre 'Nombre d'élément par recherche' ne fonctionne pas sur mon environnement. Peu importe la valeur choisit, il y a toujours 10 éléments affichés.

Merci d'avance pour votre retour, en espérant que vous développez encore ce plugin.

**Comment by departement-maine-et-loire** [comment]
Bonjour

Merci pour votre retour.

L’option « bouton pour parcourir les pages suivantes » a été envisagée et abandonnée en phase projet.
L’idée était de concevoir un plugin simple et léger, sachant qu’il y a la possibilité de visualiser les recherches complètes en cliquant sur l’en-tête.
Concernant le 2ᵉ point, il est possible que ce soit lié à la valeur « Nombre de filtres » accessible dans le menu  Configuration/Plugins/MyCustomView.

Pour le dernier point, nous espérons pouvoir reprendre le développement dès lors où nous aurons les ressources nécessaires.

**Comment by c-theo** [comment]
Pour le bouton pour parcourir les pages, j'ai besoin de cette fonctionnalité dans mon environnement, pourriez-vous s'il vous plaît m'orienter sur les fichiers qu'il faudrait modifier, afin que j'essai de le faire de mon côté ?

Pour le 2eme point, j'ai essayé de modifier la valeur 'Nombre de filtres', sans succès.

Merci et bonne journée

**Comment by departement-maine-et-loire** [comment]
Bonjour

Pouvez-vous effectuer les vérifications suivantes et me retourner les infos :
- Quelle est la version GLPI utilisée ?
- Est-ce que le bug a été reproduit sur un autre environnement GLPI ?
- Est-ce que le mode debug (mode admin) indique des erreurs ? Si oui, lesquelles ?
- Est-ce que les logs serveurs remontent des erreurs ? Si oui lesquelles ?
- Est-ce que le mode console (F12) de votre navigateur vous remonte des erreurs ? Si oui, lesquelles ?
- Est-ce que les droits sont effectifs sur le profil utilisé (Administration/Profils puis onglet "Ma vue personnalisée")
- Pouvez-vous essayer avec un autre navigateur vidé de son cache (afin d'éliminer cette cause, même si c'est peu probable) ?

En dernier recours, essayer de désinstaller/réinstaller le plugin.

Vos réponses nous aideront peut-être à identifier votre problème et seront utilisées pour une future mise à jour (je l'espère cette année).
Pour votre demande liée au développement de boutons, comme indiqué plus haut, je suis en attente de ressource.

Je ne peux que vous indiquer la localisation des sources (/usr/share/glpi/plugins/mycustomview)

Merci de votre contribution.
