### ISSUE TITLE
MyCustomView et GLPI v10

### ISSUE THREAD

**Issue by corzakiewicz** [departement-maine-et-loire/mycustomview#8]
Bonjour,

Je teste actuellement GPLI v10 et me rend compte que le plugin MyCustomView est installé et actif.
L'accès à la vue MyCustomView fonctionne, on y voit un tableau de bord vide avec le message "Vous n'avez actuellement aucun filtre sauvergardé dans cette vue".
![image](https://github.com/departement-maine-et-loire/mycustomview/assets/75740722/c6b88398-4014-4ab8-85c9-3588a308c2a9)
Je me rends donc sur "Modifier" puis "Afficher la liste", là je sélectionne une recherche sauvegardée puis je clique sur le bouton "+" afin de l'ajouter dans ma vue. La page se rafraîcit et je suis redirigée à nouveau sur la page initiale qui m'indique "Vous n'avez actuellement aucun filtre sauvegardé dans cette vue".

Est-ce que MyCustomView fonctionne avec GLPI v10 ?
(je me dis qu'il ne doit pas me manquer grand chose pour que ça fonctionne).

J'en profite pour vous faire un retour d'expérience après presque deux ans d'utilisation de ce plugin. Celui-ci nous aide grandement au quotidien, il facilite beaucoup l'accès aux différents tickets car nous pouvons avoir sur la même page les nouveau tickets, les tickets qui nous sont assignés individuellement et les tickets pour lesquels les utilisateurs ont répondu.  Merci à vous.

**Comment by departement-maine-et-loire** [comment]
Bonjour

Merci beaucoup pour votre retour positif.

N’ayant pas trouvé d’équivalent, nous avons décidé de développer ce plugin il y a maintenant plus de 2 ans.
Il est donc compatible que pour GLPI 9.2 à 9.5.

Nous avons l’objectif de publier une version pour la  V10 car nous constatons le même comportement que vous.
Toutefois, nous n’avons pas pour l’instant les ressources nécessaires pour effectuer le développement (et pas en mesure de communiquer une date de disponibilité).

Cordialement

**Comment by corzakiewicz** [comment]
Merci pour votre retour.
Si ça peut aider, voici ce que je viens de découvrir en activant la console développeur de mon navigateur Chrome :

1. Lorsque je clique sur le bouton Enregistrer du plugin MyCustomView, erreur de chargement de l'URL suivante :
https://monserveurglpi/plugins/mycustomview//plugins/mycustomview/css/theme.default.min.css?v=baabb917aebdebd9e06a36fa8d90d1fbe02a795c
--> on constate que l'URL est "faussée" par deux fois "/plugins/mycustomview"

2. Lorsque je cliquer sur le bouton Ajouter (pour ajouter une recherche à la liste My Custom View, erreur de chargement de la même URL :
https://monserveurglpi/plugins/mycustomview//plugins/mycustomview/css/theme.default.min.css?v=baabb917aebdebd9e06a36fa8d90d1fbe02a795c
--> ici aussi on constate que l'URL est "faussée" par deux fois "/plugins/mycustomview"
